### PR TITLE
Stacksmith merger

### PR DESCRIPTION
**Pull request by sameersbn**

### CODE REVIEW

**Comment by prydonius** [comment]
retest this please

**Comment by prydonius** [comment]
@sameersbn may need to bump the sleep time here

**Comment by sameersbn** [comment]
@prydonius need to debug the tests on the CI server. 
Please dont trigger the tests again. It freezes the CI

**Comment by sameersbn** [comment]
@prydonius okay to merge

**Comment by prydonius** [comment]
lgtm :+1:

**Pull request merged**
